### ISSUE TITLE
VS2017: "You can improve 'Startup' performance by auto hiding or collapsing 'AxoCover' window."

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoCover#126]
VS2017 has begun reporting at startup "You can improve 'Startup' performance by auto hiding or collapsing 'AxoCover' window." due to AxoCover starting up too slowly.

![image](https://user-images.githubusercontent.com/1912242/31361669-03850ef4-ad1a-11e7-90ab-c01bd867e12a.png)

**Comment by axodox** [comment]
OK, I have already planned this, this warning will push me over to actually do it.

**Comment by axodox** [comment]
Hmm, it seems the API required to specify async loading / startup requires VS2017. So I cannot use it - well I want to support from 2012, and I do not plan to fork it either - especially since VS extension uploads are done manually.

I will do some measurements, but this 5 seconds on average seems to be out of touch, since nothing is really done on loading, and every bit of IO and other lengthy operation is done on background threads.

I could imagine that if you open a solution, loading the highlighting and test tree could be slower since it is WPF, but that is my best call.

**Comment by axodox** [comment]
I have found that setting up the log window on another thread can save a second or more. Unfortunately WPF/XAML parsing takes 0.5-1.5 seconds, but since that does not depend on VS, that might not even be the source of the problem. Anyways, I have some ideas, but those are more drastic, so lets try this one first and see if it helps.

**Comment by NeilJustice** [comment]
Thanks for the performance optimization. I don't see "You can improve 'Startup' performance by auto hiding or collapsing 'AxoCover' window." anymore.
